<?php
/**
 * AuditLogEntryJsonldAuditLogEntryWriteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\AuditLogService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Audit Log API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VentureLeap\AuditLogService;

/**
 * AuditLogEntryJsonldAuditLogEntryWriteTest Class Doc Comment
 *
 * @category    Class
 * @description AuditLogEntryJsonldAuditLogEntryWrite
 * @package     VentureLeap\AuditLogService
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuditLogEntryJsonldAuditLogEntryWriteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuditLogEntryJsonldAuditLogEntryWrite"
     */
    public function testAuditLogEntryJsonldAuditLogEntryWrite()
    {
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "user_uuid"
     */
    public function testPropertyUserUuid()
    {
    }

    /**
     * Test attribute "entity_uuid"
     */
    public function testPropertyEntityUuid()
    {
    }

    /**
     * Test attribute "entity_type"
     */
    public function testPropertyEntityType()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "body"
     */
    public function testPropertyBody()
    {
    }

    /**
     * Test attribute "entry_type"
     */
    public function testPropertyEntryType()
    {
    }
}
